spring:
  # Email provider config
  mail:
    host: smtp.mailtrap.io
    protocol: smtp
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      - mail.smtp.auth: no
      - mail.smtp.starttls.enable: true

  # Enable support of multi-part uploads.
  http:
    multipart:
      enable: true
      location: /
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false

app:
  recipient: dummy@qualquercoisa.com.br
